name: handwritten_digit_scanner
description: A polished digit scanner for CSC661
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core Logic
  camera: ^0.10.5
  flutter_tflite: ^1.0.1
  image: ^3.2.0  # For resizing/grayscale
  signature: ^5.0.0
  shared_preferences: ^2.2.2
  
  # UI/UX
  google_fonts: ^6.1.0
  intl: ^0.19.0   # For dates in history

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mnist.tflite
    - assets/labels.txt
    - assets/background.jpg